[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --flash-size 4mb --monitor"

[env]
ESP_IDF_VERSION = "v5.2"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults;moondeck-app/sdkconfig.partitions", relative = true }
ESP_IDF_SYS_ROOT_CRATE = "moondeck-app"

[unstable]
build-std = ["std", "panic_abort"]

[profile.release]
opt-level = "s"
lto = "fat"

[profile.dev]
debug = true
opt-level = "z"
